version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      - PORT
      - COUNTER
      - CLIENT_ID
      - CLIENT_SECRET
      - REDIRECT_URI
      - ACCESS_TOKEN
      - REFRESH_TOKEN
      - CHANNEL
      - API_KEY
    ports:
      - $PORT:$PORT