version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tjan-speedrun
    restart: unless-stopped
    environment:
      - PORT
      - COUNTER
    expose:
      - $PORT
    networks:
      - main-network
networks:
  main-network:
    name: main-network
    external: true
  
