version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tjan-speedrun
    restart: unless-stopped
    environment:
      - PORT
      - COUNTER
      - CLIENT_ID
      - CLIENT_SECRET
      - REDIRECT_URI
      - ACCESS_TOKEN
      - REFRESH_TOKEN
      - CHANNEL
    expose:
      - $PORT
    networks:
      - main-network
networks:
  main-network:
    name: main-network
    external: true
