version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - PORT
      - COUNTER
    ports:
      - $PORT:$PORT

  